import { create } from 'zustand';
import type { FeatureCollection } from 'geojson';
import { feature } from 'topojson-client';
import type { Topology, GeometryCollection } from 'topojson-specification';
import type { ProjectionVariant } from '../utils/projectionVariants';
import { variantDef, defaultVariant } from '../utils/projectionVariants';

export type ProjectionFamily = 'cylindrical' | 'conic' | 'azimuthal';
export type DistortionModel = 'conformal' | 'equalArea' | 'equidistant';

// Light-source modes for the azimuthal family. The projection is generated by a
// point light whose position defines it: `center` → gnomonic, `antipode` →
// stereographic, `infinity` → orthographic (parallel beams); `math` falls back
// to the analytic distortion-selected projection.
// The cylindrical and conic families have no separate light selector (the
// cylinder is unrolled onto a tube; the cone's apex is the light).
export type AzimuthalLight = 'center' | 'antipode' | 'infinity' | 'math';

// Default distortion per family: cylindrical → conformal, conic → equidistant,
// azimuthal → equal-area.
export const DEFAULT_DISTORTION: Record<ProjectionFamily, DistortionModel> = {
  cylindrical: 'conformal',
  conic: 'equidistant',
  azimuthal: 'equalArea',
};

export interface ProjectionParams {
  variant?: ProjectionVariant;
  family: ProjectionFamily;
  distortion: DistortionModel;
  lambda0: number; // -180...180  (central meridian)
  phiOrigin: number; // -90...90   (central latitude)
  scaleFactor: number; // aux-figure immersion; slider 0.9...1.1 (conic/azimuthal) or 0.5...1.0 for cylindrical (1.0 = Earth-diameter cylinder, 0.5 = half)
  falseEasting: number; // -1000...1000
  falseNorthing: number; // -1000...1000
  gamma: number; // -180...180  (tilt / third rotation → oblique & transverse aspects)
  stdParallel2: number | null; // φ2; null = tangent surface (single standard parallel)
  azLight: AzimuthalLight; // light-source mode for the azimuthal family
}

export function defaultParamsForFamily(family: ProjectionFamily): ProjectionParams {
  const v = defaultVariant(family);
  const def = variantDef(v);
  return {
    variant: v,
    family: def.family,
    distortion: def.distortion,
    lambda0: 0,
    phiOrigin: 0,
    scaleFactor: def.lockedScaleFactor ?? 1,
    falseEasting: 0,
    falseNorthing: 0,
    gamma: def.lockedGamma ?? 0,
    stdParallel2: def.lockedStdParallel2 ?? null,
    azLight: def.azLight,
  };
}

interface AppState extends ProjectionParams {
  showTissot: boolean;
  showBorders: boolean;
  // White lines marking where the auxiliary (developable) surface intersects
  // the globe, drawn on the 2D map (the 3D scene always draws them).
  showIntersection: boolean;
  // 3D globe keeps the lightweight 110m land; 2D map uses the detailed 50m datasets.
  geoJsonData: FeatureCollection | null;
  land50GeoJson: FeatureCollection | null;
  countriesGeoJson: FeatureCollection | null;
  // True while the bundled geodata is being fetched (used to show a loading hint
  // and to ignore a late response after unmount / re-fetch).
  geoLoading: boolean;
  // 110m country borders, used by the lightweight (non-detailed) 2D map.
  countries110GeoJson: FeatureCollection | null;
  // When true the 2D map uses the detailed 50m land + country borders; otherwise the
  // lightweight 110m land (shared with the 3D globe) is drawn without borders.
  detailedMap: boolean;

  // The point currently hovered in either the 2D map or the 3D globe, shared so
  // the other view can mirror the highlight (docs/specification.md §2 cross-linking).
  // `hoverSource` records which view set it, so the projection ray is drawn only
  // when the 2D map is hovered (the 3D globe mirrors the marker, not the ray).
  hoverLonLat: [number, number] | null;
  hoverSource: 'globe' | 'map' | null;
  setHoverLonLat: (v: [number, number] | null, source?: 'globe' | 'map') => void;
  // Toggle the cursor-driven projection ray (drawn in the 3D scene only while the
  // 2D map is hovered). Independent of the always-on central-meridian ray fan.
  showHoverRay: boolean;
  setShowHoverRay: (value: boolean) => void;

  setParam: <K extends keyof ProjectionParams>(key: K, value: ProjectionParams[K]) => void;
  setVariant: (v: ProjectionVariant) => void;
  setShowTissot: (value: boolean) => void;
  setShowBorders: (value: boolean) => void;
  setShowIntersection: (value: boolean) => void;
  setDetailedMap: (value: boolean) => void;
  setFamily: (family: ProjectionFamily) => void;
  resetParams: () => void;
  loadGeoData: () => Promise<void>;
  applyPreset: (preset: Partial<ProjectionParams>) => void;
}

export const useAppStore = create<AppState>((set, get) => ({
  ...defaultParamsForFamily('cylindrical'),
  showTissot: false,
  showBorders: false,
  showIntersection: false,
  geoJsonData: null,
  land50GeoJson: null,
  countriesGeoJson: null,
  countries110GeoJson: null,
  geoLoading: false,
  detailedMap: false,
  hoverLonLat: null,
  hoverSource: null,
  showHoverRay: false,
  setHoverLonLat: (v, source) => set({ hoverLonLat: v, hoverSource: source ?? null }),
  setShowHoverRay: (value) => set({ showHoverRay: value }),

  setParam: (key, value) => {
    if (key === 'distortion' && value === 'conformal') {
      const s = get();
      if (s.family === 'azimuthal' && s.azLight !== 'antipode') {
        set({ distortion: value, azLight: 'antipode' });
        return;
      }
    }
    set({ [key]: value } as Pick<AppState, typeof key>);
  },
  setVariant: (v) => {
    const def = variantDef(v);
    set({
      variant: v,
      family: def.family,
      distortion: def.distortion,
      azLight: def.azLight,
      gamma: def.lockedGamma ?? 0,
      scaleFactor: def.lockedScaleFactor ?? 1,
      phiOrigin: 0,
      lambda0: 0,
      stdParallel2: def.lockedStdParallel2 ?? null,
    });
  },
  setShowTissot: (value) => set({ showTissot: value }),
  setShowBorders: (value) => set({ showBorders: value }),
  setShowIntersection: (value) => set({ showIntersection: value }),
  setDetailedMap: (value) => set({ detailedMap: value }),
  setFamily: (family) => set({ ...defaultParamsForFamily(family) }),
  resetParams: () => set((s) => {
    const v = defaultVariant(s.family);
    const def = variantDef(v);
    return {
      variant: v,
      family: def.family,
      distortion: def.distortion,
      azLight: def.azLight,
      lambda0: 0,
      phiOrigin: 0,
      scaleFactor: def.lockedScaleFactor ?? 1,
      falseEasting: 0,
      falseNorthing: 0,
      gamma: def.lockedGamma ?? 0,
      stdParallel2: def.lockedStdParallel2 ?? null,
    };
  }),
  applyPreset: (preset: Partial<ProjectionParams>) => set({ ...preset }),
  loadGeoData: async () => {
    // A monotonically increasing token lets a later call supersede an earlier one
    // (e.g. on a fast remount): only the most recent fetch may commit its result.
    const token = (useAppStore.getState() as AppState & { _geoToken?: number })._geoToken ?? 0;
    const next = token + 1;
    (useAppStore.getState() as AppState & { _geoToken?: number })._geoToken = next;
    set({ geoLoading: true });

    const load = async (url: string, object: string): Promise<FeatureCollection | null> => {
      try {
        const response = await fetch(url);
        if (!response.ok) throw new Error(`Failed to load ${url}: ${response.status}`);
        const topology = (await response.json()) as Topology;
        const geometry = topology.objects[object] as GeometryCollection;
        return feature(topology, geometry) as FeatureCollection;
      } catch (err) {
        console.error('loadGeoData failed:', url, err);
        return null;
      }
    };
    const [land110, land50, countries, countries110] = await Promise.all([
      load('/world-110m.topojson', 'land'),
      load('/land-50m.json', 'land'),
      load('/countries-50m.json', 'countries'),
      load('/countries-110m.json', 'countries'),
    ]);
    // Ignore stale results: if a newer load started while we were fetching, the
    // newer call owns the committed state and this one must not overwrite it.
    if ((useAppStore.getState() as AppState & { _geoToken?: number })._geoToken !== next) return;
    set({
      geoJsonData: land110,
      land50GeoJson: land50,
      countriesGeoJson: countries,
      countries110GeoJson: countries110,
      geoLoading: false,
    });
  },
}));
