import { create } from 'zustand';
import type { FeatureCollection } from 'geojson';
import { feature } from 'topojson-client';
import type { Topology, GeometryCollection } from 'topojson-specification';

export type ProjectionFamily = 'cylindrical' | 'conic' | 'azimuthal';
export type DistortionModel = 'conformal' | 'equalArea' | 'equidistant';

// Interactive light source modes. The azimuthal family is generated by a point
// light whose position defines the projection (centre → gnomonic, antipode →
// stereographic, infinity → orthographic); `math` falls back to the analytic
// distortion-selected projection with dashed formula vectors. The cylindrical
// family is generated by a linear source (a rod through the globe): `ns` →
// standard, `transverse` → rotated 90°, `oblique` → inclined; `math` is the
// analytic Mercator/equal-area/equidistant. The conic family is always a cone
// with its apex at the light (no separate light selector).
export type AzimuthalLight = 'center' | 'antipode' | 'infinity' | 'math';
export type CylindricalLight = 'ns' | 'transverse' | 'oblique' | 'math';

// Default distortion per family: cylindrical → conformal, conic → equidistant,
// azimuthal → equal-area.
export const DEFAULT_DISTORTION: Record<ProjectionFamily, DistortionModel> = {
  cylindrical: 'conformal',
  conic: 'equidistant',
  azimuthal: 'equalArea',
};

export interface ProjectionParams {
  family: ProjectionFamily;
  distortion: DistortionModel;
  lambda0: number; // -180...180  (central meridian)
  phiOrigin: number; // -90...90   (central latitude)
  scaleFactor: number; // 0.9...1.1 (aux-figure immersion)
  falseEasting: number; // -1000...1000
  falseNorthing: number; // -1000...1000
  gamma: number; // -180...180  (tilt / third rotation → oblique & transverse aspects)
  stdParallel2: number | null; // φ2; null = tangent surface (single standard parallel)
  azLight: AzimuthalLight; // light-source mode for the azimuthal family
  cylLight: CylindricalLight; // light-source (rod) mode for the cylindrical family
}

export function defaultParamsForFamily(family: ProjectionFamily): ProjectionParams {
  return {
    family,
    distortion: DEFAULT_DISTORTION[family],
    lambda0: 0,
    phiOrigin: 0,
    scaleFactor: 1,
    falseEasting: 0,
    falseNorthing: 0,
    gamma: 0,
    stdParallel2: null,
    azLight: 'math',
    cylLight: 'math',
  };
}

interface AppState extends ProjectionParams {
  showTissot: boolean;
  showBorders: boolean;
  // 3D globe keeps the lightweight 110m land; 2D map uses the detailed 50m datasets.
  geoJsonData: FeatureCollection | null;
  land50GeoJson: FeatureCollection | null;
  countriesGeoJson: FeatureCollection | null;
  // 110m country borders, used by the lightweight (non-detailed) 2D map.
  countries110GeoJson: FeatureCollection | null;
  // When true the 2D map uses the detailed 50m land + country borders; otherwise the
  // lightweight 110m land (shared with the 3D globe) is drawn without borders.
  detailedMap: boolean;

  setParam: <K extends keyof ProjectionParams>(key: K, value: ProjectionParams[K]) => void;
  setShowTissot: (value: boolean) => void;
  setShowBorders: (value: boolean) => void;
  setDetailedMap: (value: boolean) => void;
  setFamily: (family: ProjectionFamily) => void;
  resetParams: () => void;
  loadGeoData: () => Promise<void>;
  applyPreset: (preset: Partial<ProjectionParams>) => void;
}

export const useAppStore = create<AppState>((set) => ({
  ...defaultParamsForFamily('cylindrical'),
  showTissot: false,
  showBorders: false,
  geoJsonData: null,
  land50GeoJson: null,
  countriesGeoJson: null,
  countries110GeoJson: null,
  detailedMap: false,

  setParam: (key, value) => set({ [key]: value } as Pick<AppState, typeof key>),
  setShowTissot: (value) => set({ showTissot: value }),
  setShowBorders: (value) => set({ showBorders: value }),
  setDetailedMap: (value) => set({ detailedMap: value }),
  setFamily: (family) => set({ ...defaultParamsForFamily(family) }),
  resetParams: () => set((s) => ({ ...defaultParamsForFamily(s.family) })),
  applyPreset: (preset: Partial<ProjectionParams>) => set({ ...preset }),
  loadGeoData: async () => {
    const load = async (url: string, object: string): Promise<FeatureCollection | null> => {
      try {
        const response = await fetch(url);
        if (!response.ok) throw new Error(`Failed to load ${url}: ${response.status}`);
        const topology = (await response.json()) as Topology;
        const geometry = topology.objects[object] as GeometryCollection;
        return feature(topology, geometry) as FeatureCollection;
      } catch (err) {
        console.error('loadGeoData failed:', url, err);
        return null;
      }
    };
    const [land110, land50, countries, countries110] = await Promise.all([
      load('/world-110m.topojson', 'land'),
      load('/land-50m.json', 'land'),
      load('/countries-50m.json', 'countries'),
      load('/countries-110m.json', 'countries'),
    ]);
    set({
      geoJsonData: land110,
      land50GeoJson: land50,
      countriesGeoJson: countries,
      countries110GeoJson: countries110,
    });
  },
}));
