declare module 'd3-geo-projection' {
  import type { GeoProjection, GeoRawProjection } from 'd3-geo';

  function geoAitoff(): GeoProjection;
  function geoAitoffRaw(): GeoRawProjection;
  function geoBoggs(): GeoProjection;
  function geoBoggsRaw(): GeoRawProjection;
  function geoBonne(): GeoProjection;
  function geoBonneRaw(): GeoRawProjection;
  function geoBromley(): GeoProjection;
  function geoBromleyRaw(): GeoRawProjection;
  function geoCollignon(): GeoProjection;
  function geoCollignonRaw(): GeoRawProjection;
  function geoCraster(): GeoProjection;
  function geoCrasterRaw(): GeoRawProjection;
  function geoCylindricalEqualArea(): GeoProjection;
  function geoCylindricalEqualAreaRaw(): GeoRawProjection;
  function geoEckert1(): GeoProjection;
  function geoEckert2(): GeoProjection;
  function geoEckert3(): GeoProjection;
  function geoEckert4(): GeoProjection;
  function geoEckert5(): GeoProjection;
  function geoEckert6(): GeoProjection;
  function geoEisenlohr(): GeoProjection;
  function geoFahey(): GeoProjection;
  function geoFoucaut(): GeoProjection;
  function geoFoucautSinusoidal(): GeoProjection;
  function geoGinzburg4(): GeoProjection;
  function geoGinzburg5(): GeoProjection;
  function geoGinzburg6(): GeoProjection;
  function geoGinzburg8(): GeoProjection;
  function geoGinzburg9(): GeoProjection;
  function geoGuyou(): GeoProjection;
  function geoHammer(): GeoProjection;
  function geoHammerRaw(): GeoRawProjection;
  function geoHealpix(): GeoProjection;
  function geoHill(): GeoProjection;
  function geoHomolosine(): GeoProjection;
  function geoKavrayskiy7(): GeoProjection;
  function geoLagrange(): GeoProjection;
  function geoLagrangeRaw(): GeoRawProjection;
  function geoLoximuthal(): GeoProjection;
  function geoLoximuthalRaw(): GeoRawProjection;
  function geoMiller(): GeoProjection;
  function geoMillerRaw(): GeoRawProjection;
  function geoMollweide(): GeoProjection;
  function geoMollweideRaw(): GeoRawProjection;
  function geoNaturalEarth2(): GeoProjection;
  function geoNaturalEarth2Raw(): GeoRawProjection;
  function geoNellHammer(): GeoProjection;
  function geoPatterson(): GeoProjection;
  function geoPolyconic(): GeoProjection;
  function geoPolyconicRaw(): GeoRawProjection;
  function geoRobinson(): GeoProjection;
  function geoRobinsonRaw(): GeoRawProjection;
  function geoSatellite(): GeoProjection;
  function geoSatelliteRaw(distance: number, angle?: number): GeoRawProjection;
  function geoSinuMollweide(): GeoProjection;
  function geoSinusoidal(): GeoProjection;
  function geoSinusoidalRaw(): GeoRawProjection;
  function geoTimes(): GeoProjection;
  function geoVanDerGrinten(): GeoProjection;
  function geoVanDerGrintenRaw(): GeoRawProjection;
  function geoVanDerGrinten2(): GeoProjection;
  function geoVanDerGrinten3(): GeoProjection;
  function geoVanDerGrinten4(): GeoProjection;
  function geoWagner4(): GeoProjection;
  function geoWagner6(): GeoProjection;
  function geoWagner7(): GeoProjection;
  function geoWiechel(): GeoProjection;
  function geoWinkel3(): GeoProjection;

  // Interrupted projections
  function geoInterruptedBoggs(): GeoProjection;
  function geoInterruptedHomolosine(): GeoProjection;
  function geoInterruptedMollweide(): GeoProjection;
  function geoInterruptedMollweideHemispheres(): GeoProjection;
  function geoInterruptedSinuMollweide(): GeoProjection;
  function geoInterruptedSinusoidal(): GeoProjection;

  // Polyhedral projections
  function geoPolyhedralButterfly(): GeoProjection;
  function geoPolyhedralCollignon(): GeoProjection;
  function geoPolyhedralWaterman(): GeoProjection;

  // Quincuncial projections
  function geoPeirceQuincuncial(): GeoProjection;
  function geoGringortenQuincuncial(): GeoProjection;

  // Special azimuthal
  function geoTwoPointAzimuthal(): GeoProjection;
  function geoTwoPointAzimuthalRaw(): GeoRawProjection;
  function geoTwoPointAzimuthalUsa(): GeoProjection;
  function geoTwoPointEquidistant(): GeoProjection;
  function geoTwoPointEquidistantRaw(): GeoRawProjection;
  function geoTwoPointEquidistantUsa(): GeoProjection;

  // Other
  function geoGringorten(): GeoProjection;
  function geoArmadillo(): GeoProjection;
  function geoAugust(): GeoProjection;
  function geoBaker(): GeoProjection;
  function geoBerghaus(): GeoProjection;
  function geoBertin1953(): GeoProjection;
  function geoBottomley(): GeoProjection;
  function geoChamberlin(): GeoProjection;
  function geoChamberlinAfrica(): GeoProjection;
  function geoCraig(): GeoProjection;
  function geoCylindricalStereographic(): GeoProjection;
  function geoGilbert(): GeoProjection;
  function geoGingery(): GeoProjection;
  function geoHammerRetroazimuthal(): GeoProjection;
  function geoHufnagel(): GeoProjection;
  function geoHyperelliptical(): GeoProjection;
  function geoLarrivee(): GeoProjection;
  function geoLaskowski(): GeoProjection;
  function geoLittrow(): GeoProjection;
  function geoModifiedStereographic(): GeoProjection;
  function geoModifiedStereographicAlaska(): GeoProjection;
  function geoModifiedStereographicGs48(): GeoProjection;
  function geoModifiedStereographicGs50(): GeoProjection;
  function geoModifiedStereographicMiller(): GeoProjection;
  function geoModifiedStereographicLee(): GeoProjection;
  function geoMtFlatPolarParabolic(): GeoProjection;
  function geoMtFlatPolarQuartic(): GeoProjection;
  function geoMtFlatPolarSinusoidal(): GeoProjection;
  function geoNicolosi(): GeoProjection;
  function geoQuantize(): GeoProjection;
  function geoRectangularPolyconic(): GeoProjection;
  function geoRectangularPolyconicRaw(): GeoRawProjection;
  function geoStitch(): GeoProjection;
  function geoInterruptedQuarticAuthalic(): GeoProjection;
  function geoProject(): GeoProjection;
  function geoInterrupt(): GeoProjection;
  function geoQuincuncial(): GeoProjection;
  function geoPolyhedral(): GeoProjection;
}
